### PR TITLE
64-bit + unsigned integer support

### PR DESCRIPTION
**Pull request by arnetheduck**
Depends on https://github.com/filcuc/dotherside/pull/93

### CODE REVIEW

**Comment by filcuc** [comment]
I think we should first do a DOtherSide bump before merging this one

**Comment by filcuc** [comment]
That said the pull is fine

**Review by filcuc — APPROVED** [review]

**Comment by filcuc** [comment]
@arnetheduck first sorry for the lag but adding support for  QObject signal and slot connections took me too long because i wanted also QThread support (but i postponed it). I've release a new DOtherSide official release 0.8.0 and a new NimQml release 0.9.0. Can you recheck your changes after a rebase to 0.9.0?

**Comment by arnetheduck** [comment]
this PR just exposes a few new functions - as long as it doesn't conflict, it should continue to work - I've moved on from it so it might take a while before I have time to rebase, but I imagine it makes sense to people in general to have this functionality exposed

**Pull request closed without merging**
